config/routes.rb
Rails.application.routes.draw do

  resources :ngpost do 
    member do
      post :add_vote
      post :minus_vote
    end
  end
  

  get 'post_list' => "ngpost#post_list"
  get 'get_ip' => "ngpost#get_ip"
  get 'gem_store' => "gem_store#index"
  
  resources :posts do 
    member do 
      post :add_vote
      post :minus_vote
    end
    
  end
  
  get 'dashboard/index'
  root 'posts#index'
  
  namespace :api do
    resources :events, only: [:index, :create, :update] , :controller => "/events" do
      collection do
        get :search
      end
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :vote_records
  attr_accessor :can_vote_tag

  def as_json(options = {})
  super options.merge(methods: [:can_vote_tag])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :set_post, only: [:show, :edit, :update, :destroy, :add_vote, :minus_vote]
   Vote_time_limit = 5
   helper_method :can_vote_any_more?
   # GET /posts
   # GET /posts.json
   def index
      @items_per_page = 10
      @posts = Post.all.order(:id).includes(:vote_records).page(params[:page]).per(@items_per_page)
      @record = Post.new
      #if env["HTTP_X_FORWARDED_FOR"] = nil?
      @remote_ip = request.env["HTTP_X_FORWARDED_FOR"].split(",")[0] || request.remote_ip.split(",")[0] unless request.env["HTTP_X_FORWARDED_FOR"].nil?
      @user = VoteRecord.find_by(:ip => "#{@remote_ip}")
      if @user.nil? 
      session[:visitor_id] ||= SecureRandom.uuid
      else
      session[:visitor_id] = @user.uuid
      end
      @uuid = session[:visitor_id]
      @limit = Vote_time_limit
      @check_list = VoteRecord.group(:post_id).where(:ip => "#{@remote_ip}").count

   end
   
   # GET /posts/1
   # GET /posts/1.json
   def show
   end
   
   # GET /posts/new
   def new
      @post = Post.new
   end
   
   # GET /posts/1/edit
   def edit
   end
   
   # POST /posts
   # POST /posts.json
   def create
      @post = Post.new(post_params)
      
      respond_to do |format|
         if @post.save
            format.html { redirect_to @post, notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
         else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
         end
      end
      
   end
   
   # PATCH/PUT /posts/1
   # PATCH/PUT /posts/1.json
   def update
      respond_to do |format|
         if @post.update(post_params)
            format.html { redirect_to @post, notice: 'Post was successfully updated.' }
            format.json { render :show, status: :ok, location: @post }
         else
            format.html { render :edit }
            format.json { render json: @post.errors, status: :unprocessable_entity }
         end
      end
      
   end
   
   # DELETE /posts/1
   # DELETE /posts/1.json
   def destroy
      @post.destroy
         respond_to do |format|
         format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
         format.json { head :no_content }
      end
   end

   def add_vote
    @switch = can_vote_any_more?(@post)
    if @switch
    @post.goodvote += 1 
    @post.save
    record_vote_data(@post, 1)
    end
    respond_to do |format|
      # if the response fomat is html, redirect as usual
      format.html { redirect_to root_path }
      # if the response format is javascript, do something else...
      format.js { }
    end
    
   end

   def minus_vote
    # 如果總分不允許負分出現的話，這邊要再多判斷  badvote 分數是不是已經大於 goodvote 分數
    @switch = can_vote_any_more?(@post)
    if @switch 
      @post.badvote += 1 
      @post.save
      record_vote_data(@post, -1)   
    end    
    respond_to do |format|
      # if the response fomat is html, redirect as usual
      format.html { redirect_to root_path }
      # if the response format is javascript, do something else...
      format.js { }
    end
   end
 
   private
   
   # Use callbacks to share common setup or constraints between actions.
   def set_post
      @post = Post.find(params[:id])
      @limit = Vote_time_limit
   end
   
   # Never trust parameters from the scary internet, only allow the white list through.
   def post_params
      params.require(:post).permit(:title, :content)
   end

   def record_vote_data(post , idea)
    @vote_record = post.vote_records.build
    @vote_record.uuid = session[:visitor_id]
    @vote_record.ip = request.env["HTTP_X_FORWARDED_FOR"].split(",")[0] unless request.env["HTTP_X_FORWARDED_FOR"].nil?
    @vote_record.idea = idea 
    @vote_record.name = (@vote_record.ip.nil?) ? "訪客 " : "訪客 " + @vote_record.ip
    @vote_record.save       
   end

   def can_vote_any_more?(post)
    remote_ip = request.env["HTTP_X_FORWARDED_FOR"].split(",")[0] unless request.env["HTTP_X_FORWARDED_FOR"].nil?
    if remote_ip.nil? || remote_ip == ""
      VoteRecord.where(:uuid => "#{session[:visitor_id]}", :post_id => post.id ).count < Vote_time_limit ? true : false        
    else
      VoteRecord.where(:ip => "#{remote_ip}", :post_id => post.id ).count < Vote_time_limit ? true : false
    end      
   end


end

app/helpers/posts_helper.rb
module PostsHelper

  def transform_to_idea_icon(idea)
    if idea == "1" 
      return raw("<span class=\"glyphicon glyphicon-thumbs-up icon-thumbs-up \" aria-hidden=\"true\"></span>")
    elsif idea == "-1" 
      return raw("<span class=\"glyphicon glyphicon-thumbs-down icon-thumbs-down \" aria-hidden=\"true\"></span>")
    end

  end
  

end

app/views/posts/_form.html.erb
    <%= form_for(@post) do |f| %>
      <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </div>
      <div class="field">
        <%= f.label :content %><br>
        <%= f.text_area :content %>
      </div>
      <div class="field">
        <%= f.label :goodvote %><br>
        <%= f.number_field :goodvote %>
      </div>
      <div class="field">
        <%= f.label :badvote %><br>
        <%= f.number_field :badvote %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>

app/views/posts/_vote_record.html.erb
<tr><td colspan="9" class="vote-comment-block"> <%= vote_record.name %> 說： <%=transform_to_idea_icon(vote_record.idea) %>  @ <%= vote_record.created_at.to_s(:long) %>  </td></tr>

app/views/posts/_vote_warning.html.erb
<tr><td colspan="4"></td><td colspan="5" class="vote-warning-block"> 本篇文章你已經投票 <%= vote_limit %> 次，不能再投了 </td></tr>

app/views/posts/add_vote.js.erb
<% if @switch %>
$(".tr-<%= j @post.id.to_s %>").after("<%= j render partial: 'vote_record', locals: { vote_record: @vote_record } %> ");
$(".tr-<%= j @post.id.to_s %>-goodvote_number").text("<%= j @post.goodvote.to_s %>");
$(".tr-<%= j @post.id.to_s %>-total_number").text("<%= j (@post.goodvote - @post.badvote).to_s %>");
<% else %>
$(".submit-<%= j @post.id.to_s %>").prop('disabled', true);
$(".article-title-<%= j @post.id.to_s %>").after("<%= j render partial: 'vote_warning', locals: { vote_limit: @limit } %> ");
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Post Vote Board</h1>
    <h3>每位訪客僅能對每一篇文章表達 <%= @limit %> 次意見，請點擊[文章好]或[文章差]按鈕</h3>
    <h2>您好 uuid： <%= session[:visitor_id] %> </h2>
    <!--<h2>IP: <%= @remote_ip %></h2>-->
    <!--<h2>IP2: <%= request.remote_ip %> </h2>-->
  </div>
  <div class="row">
  <div class="col-md-12">


<p id="notice"><%= notice %></p>
<%= paginate @posts, outer_window: 3 %>
<table class="table table-striped">
  <thead>
    <tr>Title</tr>
    <tr>
      <th>Content</th>
      <th>好</th>
      <th>不好</th>
      <th>總分</th>
      <th colspan="2">投票按鈕</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr class="article-title article-title-<%= post.id %>"><td colspan="9">文章標題：<%= post.title %></td></tr>
      <tr class=tr-<%= post.id %>>
        <% if !can_vote_any_more?(post) %>
        <%=  render partial: 'vote_warning', locals: { vote_limit: @limit } %> 
        <% end %>
        <td><%= post.content %></td>
        <td class=tr-<%= post.id %>-goodvote_number><%= post.goodvote %></td>
        <td class=tr-<%= post.id %>-badvote_number><%= post.badvote %></td>
        <td class=tr-<%= post.id %>-total_number><%= post.goodvote - post.badvote %></td>
        <td>
          <%= form_for @record, url: add_vote_post_path(post), :html => {:class => "form_vote"} do |f| %>                   
          <%= button_tag(type: "submit", class: "btn btn-xs btn-info submit-#{post.id}" , name: "commit", disabled: !can_vote_any_more?(post)) do %>          
            <span class="glyphicon glyphicon-thumbs-up icon-thumbs-up" aria-hidden=\"true\"></span> 文章好
            <% end %>
          <% end %>
        </td>
        <td>
          <%= form_for @record, url: minus_vote_post_path(post), :html => {:class => "form_vote"} do |f| %>         
          <%= button_tag(type: "submit", class: "btn btn-xs btn-warning submit-#{post.id}" , name: "commit", disabled: !can_vote_any_more?(post)) do %>          
            <span class="glyphicon glyphicon-thumbs-down icon-thumbs-down" aria-hidden=\"true\"></span> 文章差
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
              <% post.vote_records.order(:id).reverse.each do |record| %>
              <tr class=vote-record-block-<%= post.id %> >
                <td colspan="9" class="vote-comment-block"> <%= record.name %> 說： <%= transform_to_idea_icon(record.idea) %>  @ <%= record.created_at.to_s(:long) %> </td>
            
              </tr>
              <% end %>
    <% end %>
  </tbody>
</table>
<%= paginate @posts, outer_window: 3 %>
<br>
<%= link_to 'New Post', new_post_path %>
  </div>
  </div>
</div>  

app/views/posts/minus_vote.js.erb
<% if @switch %>
$(".tr-<%= j @post.id.to_s %>").after("<%= j render partial: 'vote_record', locals: { vote_record: @vote_record } %> ");
$(".tr-<%= j @post.id.to_s %>-badvote_number").text("<%= j @post.badvote.to_s %>");
$(".tr-<%= j @post.id.to_s %>-total_number").text("<%= j ((@post.goodvote - @post.badvote).to_s) %>");
<% else %>
$(".submit-<%= j @post.id.to_s %>").prop('disabled', true);
$(".article-title-<%= j @post.id.to_s %>").after("<%= j render partial: 'vote_warning', locals: { vote_limit: @limit } %> ");
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

    <h1>New Post</h1>

    <%= render 'form' %>

    <%= link_to 'Back', posts_path %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Goodvote:</strong>
  <%= @post.goodvote %>
</p>

<p>
  <strong>Badvote:</strong>
  <%= @post.badvote %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>